### ISSUE TITLE
Character not converting

### ISSUE THREAD

**Issue by jwu910** [alexandervalencia/emojify#1]
Hello,

When I type contractions such as "You're", the apostrophe character is not converting to an emoji.

**Comment by alexandervalencia** [comment]
@jwu910 Thanks for reporting this. 

This is an issue with Discord and not Emojify. There is no emoji equivalent for the apostrophe character in Discord. If you have an idea for a substitute please let us know and we'd be happy to add it!

**Comment by jwu910** [comment]
try :french_bread:
